---
title: "People"
---

## Current members of the James Lab

---
pagetitle: "People"
toc: false
listing:
  - id: supervisor
    contents: "people/supervisor/*.qmd"
    type: grid
    image-height: 225px
    grid-columns: 2
    fields: [image, title, subtitle]
    grid-item-align: center
    sort: sortby
    field-display-names: 
      started: "Started"
  - id: postdoc
    contents: "people/pdf/*.qmd"
    type: grid
    image-height: 225px
    grid-columns: 3
    sort: sortby
    fields: [image, title, subtitle, started]
    field-display-names: 
      started: "Started"
    grid-item-align: center
  - id: grad
    contents: "people/grad/*.qmd"
    type: grid
    image-height: 225px
    grid-columns: 3
    sort: start_year
    fields: [image, title, subtitle, started]
    field-display-names: 
      started: "Started"
    grid-item-align: center
  - id: staff
    contents: "people/staff/*.qmd"
    type: grid
    image-height: 225px
    grid-columns: 3
    sort: sortby
    fields: [image, title, subtitle, started]
    field-display-names: 
      started: "Started"
    grid-item-align: center   
  - id: undergrad
    contents: "people/undergrad/*.qmd"
    type: grid
    image-height: 225px
    grid-columns: 3
    sort: sortby
    fields: [image, title, subtitle, started]
    field-display-names: 
      started: "Started"
    grid-item-align: center
  - id: alumni
    contents: 
    - "people/alumni/*.qmd"
    - "people/alumni/alumni.yml"
    type: default
    sort: 
    - "ended desc"
    - "started asc"
    fields: [title, subtitle, ended, current]
    sort-ui: [title, subtitle, ended, current]
    filter-ui: [title, subtitle, ended, current]
    field-display-names: 
      title: "Name"
      subtitle: "Role"
      started: "Started in the lab"
      ended: "Ended"
      current: "Current role"
---


## Supervisor

:::{#supervisor}
:::

## Postdoctoral researchers

:::{#postdoc}
:::

## Graduate students

:::{#grad}
:::

## Staff

:::{#staff}
:::

## Undergraduate students

:::{#undergrad}
:::

## Gone but not forgotten: Lab Alumnis

:::{#alumni}
:::
