### In Review


Skretting T, Chamser L, Jones E, **James PMA**, Perrakis D, Shang C, Townsend I, Watson C. Forest fuel structure and loading over time since fuels reduction treatment in Jasper National Park, Alberta Canada using novel data sources. *International Journal of Wildland Fire*

Shakeri Z, Boucher J, Marchal J, **James PMA.** Jack pine budworm defoliation shifts fuel structure and potential fire behaviour in Eastern Canada. *Canadian Journal of Forest Research*

Brittain K, Fontenelle JP, Roe, AD, Johns RC, **James PMA**. A matter of space and time: Population genetic perspectives on outbreak dynamics. *Molecular Ecology*

Romualdi S, Brittain K, Roe AD, **James PMA**. The influence of bioinformatic filtering thresholds on population genetic inference in an outbreaking system. *Genome*

Henry M, **James PMA**, Leung B. Low-density dynamics, Allee effects, and the value of zeros. *Ecological Applications*

## Accepted

### 2026

KC Rodman, E Whitman, AA Howe, A Spannuth, KJ Barrett, CA Beinhart, Y Boucher, SU Busby, JT Carrasco, KD Clark-Wolf, MJ Corbett, JE Crouse, V Danneyrolles, PR Dappen, KT Davis, BJ Harvey, ZA Holden, SM Hood, JM Iniguez, **PMA James**, MR Kreider, MM Laughlin, KR Mahan, JE Morris, M-A Parisien, JP Roccaforte, SJ Saberi, CS Stevens-Rumann, MT Stoddard, N Tomczyk, EMN Twaddell, ST Vieira, AG Vorster, K Weimer, BD Woodward, J Woolet, JT Wooten, EL Yannayon, LL Yocom. 2026. [Right on time: evaluating accuracy and timing of burn-severity assessments to support post-fire management](publications/2026/Rodmanetal2026.pdf){target="_blank"}. **Fire Ecology** 22 (1), 154

Jourdan L, **James PMA**. 2026. [Improving Selection of Forest Fuel Metrics Using Synthetic Lidar Point Clouds](publications/2026/JourdanAndJames2026.pdf){target="_blank"}. *Ecological Informatics*.

Goldman J, Fortin M-J, **James PMA**. 2026. [Within and among years moisture availability influences wildfire burn severity in the boreal forest](publications/2026/Goldmanetal2026.pdf){target="_blank"}. *Fire Ecology*

Sturtevant B, Cooke B, Kneeshaw D, Robert L-E, **James PMA**, Fortin M-J, Wolter P, & Townsend P. 2026. [Insect defoliators trading spaces in a hemi-boreal forest: Implications for diversity-stability and ecosystem resilience](publications/2026/Sturtevantetal2026.pdf){target="_blank"}. *Ecology*.

Henry M, **James PMA**, Kneeshaw D & Leung B. 2026. [Connecting the dots: Resolving the relationship between spruce budworm population dynamics and defoliation](publications/2026/Henryetal2026.pdf){target="_blank"}. *Canadian Journal of Forest Research.*

Jourdan L, Korkola K, Piascik P, & **James PMA**. 2026. [Right on target: Monopods and polystyrene spheres as an alternative to traditional tripods for terrestrial laser scanning](publications/2026/Jourdanetal2026.pdf){target="_blank"}. *Canadian Journal of Forest Research.*

Johns RC, Edwards S, Amos-Binks L, Bowden JJ, Carleton D, Edge C, Hennigar C, **James PMA**, MacLean D, Martel V, Moise E, Morin B, Morrison A, Owens E, Stastny M, & Régnière J. 2026. [Adaptive area-wide management for suppressing spruce budworm outbreaks: Evaluating the early intervention strategy](publications/2026/Johnsetal2026.pdf){target="_blank"}. *Journal of Pest Science.*

Canelles Q, Bouchard M, Aquilué N, **James PMA**, & Filotas É. 2026. [Evaluating the effects of alternative forest management strategies on SBW outbreaks](publications/2026/Canellesetal2026.pdf){target="_blank"}. *Landscape Ecology. Def, 88, 1609-02.*

### 2025

Goldman J, Fortin M-J, **James PMA.** 2025. [Snow dynamics and forest structure interact to increase wildfire burn
severity in the boreal forest](publications/2025/Goldmanetal2025.pdf){target="_blank"}. *Forest Ecology and Management. 598, 123180.*

Korkola K, Beverly JL, **James PMA**. 2025. [Wildfire containment probability is not affected by eastern spruce budworm defoliation in Ontario, Canada](publications/2025/Korkolaetal2025.pdf){target="_blank"}. International Journal of Wildland Fire, 34(9)

Wall N, Fortin M-J, **James PMA**. [Genetic effects of landscape change on three sympatric turtle species in southern Ontario, Canada](publications/2025/Walletal2025.pdf){target="_blank"}. Conservation Genetics

**James PMA**, Fang JT, Wittische J, Cusson M, Larroque J, Roe A, Johns R. 2025. [Assigning phenologically asynchronous moths to source populations using individual genotypes](publications/2025/Jamesetal2025.pdf){target="_blank"}. Molecular Ecology

Skretting T, Chasmer L, Watson C, **James PMA**, Townshend I, Perrakis D. 2025. [Forest fuel structure and loading along a gradient of gray-phase mountain pine beetle severity in Jasper National Park, Alberta, Canada](publications/2025/Skrettingetal2025.pdf){target="_blank"}. Canadian Journal of Forest Research. 55, 1-14

### 2024

Korkola K, Wheatley M, Beverly J, **James PMA**, Wotton BM. 2024. [A comparative analysis of wildfire initial attack containment objectives and modelling strategies](publications/2024/Korkolaetal2024.pdf){target="_blank"}. International Journal of Wildland Fire.

Fontenelle JP, Larroque J, Legault S, Wittische J, Underwood J, **James PMA**. 2024. [Multi-year genotype characterization of eastern spruce budworm outbreaking populations from Quebec and adjacent regions](publications/2024/Fontenelleetal2024.pdf){target="_blank"}. Ecology. https://doi.org/10.1002/ecy.4466

Legault S & **James PMA**. 2024. [Spatial patterns of hyperparasitism along a latitudinal gradient of forest diversity: Insights from the spruce budworm-parasitoids community](publications/2024/LegaultAndJames2024.pdf){target="_blank"}. Environmental Entomology. 53(1): 116-126

### 2023

Romualdi DC, Wilkinson SL, **James PMA**. 2023. [On the Limited Consensus of Mountain Pine Beetle Impacts on Wildfire](publications/2023/Romualdietal2023.pdf){target="_blank"}. Landcape Ecology. 38: 2159–2178

Gandiaga F & **James PMA**. 2013. [Quantifying long-distance dispersal of an outbreaking insect species using trap capture data and phenology](publications/2023/GandiagaAndJames2023.pdf){target="_blank"}. Forest Ecology and Management. 544: 121187

Sturtevant BR, Cooke BJ, **James PMA**. 2023. [Of clockwork and catastrophes: Advances in spatiotemporal dynamics of forest Lepidoptera](publications/2023/Sturtevantetal2023.pdf){target="_blank"}. Current Opinion in Insect Science. 101005

### 2022

Hamberg LJ, Fisher JB, Ruppert J, Turečeke J, Rosen D, **James PMA**. [Assessing and modeling diurnal temperature buffering and evapotranspiration dynamics in forest restoration using ECOSTRESS thermal imaging](publications/2022/Hambergetal2022.pdf){target="_blank"}. Remote Sensing of Environment. 280, 113178

Fettig CJ, Runyon JB, Homicz CS, **James PMA**, Ulyshen MD. 2022. [Fire and Insect Interactions in North American Forests](publications/2022/Fettigetal2022.pdf){target="_blank"}. Current Forestry Reports 8: 301–316

Martin AR, Kish R, **James PMA**, Mariani RO, Schurman JS, Thomas SC & Young EN. 2022. [Beech bark disease in an unmanaged temperate forest: patterns, predictors, and impacts on ecosystem function](publications/2022/Martinetal2022.pdf){target="_blank"}. Frontiers in Forests and Global Change. v5

Risk C & **James PMA**. 2022. [Optimal cross-validation strategies for selection of spatial interpolation models for the Canadian forest fire weather index system](publications/2022/RiskAndJames2022.pdf){target="_blank"}. Earth and Space Science. 9(2), e2021EA002019.

Larroque J, Wittische J, **James PMA**. 2022. [Quantifying and predicting population connectivity of an outbreaking forest insect pest](publications/2022/Larroqueetal2022.pdf){target="_blank"}. Landscape Ecology. 37(3), 763-778.

### 2021

Landry M, Kneeshaw D, **James PMA**, Kembel S. 2022. [Spruce budworm gut bacterial communities vary among sites and host tree species in a boreal landscape](publications/2021/Landryetal2021.pdf){target="_blank"}. Journal of Biogeography. 49(2), 299-309

Legault S, Wittische J, Cusson M, Brodeur J, **James PMA**. 2021. [Landscape-scale population connectivity in two parasitoid species associated with the spruce budworm: Testing the birdfeeder effect using genetic data](publications/2021/Legaultetal2021.pdf){target="_blank"}. Molecular Ecology. 30(22), 5658-5673

Urban MC, Travis JMJ, Zurell D, Thompson PL, Synes NW, Scarpa A, Peres-Neto PR, Malchow A-K , **James PMA**, Gravel D, De Meester D, Brown D, Bocedi D, Albert CH, Gonzalez A, Hendry AP. (in press). [Coding for Life: Designing a platform for projecting and protecting global biodiversity](publications/2021/Urbanetal2021.pdf){target="_blank"}. BioScience

Germain M, De Grandpré L, Desrochers M, **James PMA**, Vepakomma U, Poulin JF, Kneeshaw D, Villard M-A. 2021. [Insectivorous songbirds as early indicators of future defoliation by spruce budworm](publications/2021/Germainetal2021.pdf){target="_blank"}. Landscape Ecology, 1-15

Canelles Q, Aquilué N, **James PMA**, Lawler J, Brotons L. 2021. [The global consequences of interactions between insect pests and other forest disturbances](publications/2021/Canellesetal2021.pdf){target="_blank"}. Landscape Ecology, 1-28

Kneeshaw D, Burton PJ, Doblas-Miranda E, **James PMA**, Tardif D, Sturtevant BR. 2021. [The visions of managing for pest-resistant landscapes: Realistic or utopic](publications/2021/Kneeshawetal2021.pdf){target="_blank"}. Current Forestry Reports, 1-17

Wittische J, Heckbert S, **James PMA**, Burton AC, Fisher JT. 2021. [Community-level modelling of boreal forest mammals in an oil sands landscape reveals how human disturbance, natural habitat, and predation shape mammal distribution](publications/2021/Wiitischeetal2021.pdf){target="_blank"}. Science of the Total Environment. 755: 142500

### 2020

Robert L-E, Sturtevant BR, Kneeshaw DD, **James PMA**, Fortin M-J, Wolter P, Townsend P, Cooke BJ. 2020. [Forest landscape structure influences the cyclic-eruptive spatial dynamics of forest tent caterpillar outbreaks](publications/2020/Robertetal2020.pdf){target="_blank"}. Ecosphere 11 (8), e03096

Carbayo HR, Pino J, Bonal R, **James PMA**, Hampe A, Espelta JM. 2020. [Insect herbivory in novel *Quercus ilex* L. forests: the role of landscape attributes, forest composition and host traits](publications/2020/Carbayoetal2020.pdf){target="_blank"}. Annals of Forest Science 77(2): 32

Larroque J, Johns R, Canape J, Morin B, **James PMA**. 2020. [Spatial genetic structure at the leading edge of a spruce budworm outbreak: the role of dispersal in outbreak spread](publications/2020/Larroqueetal2020.pdf){target="_blank"}. Forest Ecology and Management 461, 117965

Carleton D, Owens E, Blaquiere H, Bourassa S, Bowden J, Candau, J-N, DeMerchant I, Edwards S, Heustis A, **James PMA**, Kanoti A, MacQuarrie C, Martel V, Moise E, Pureswaran D, Shanks E, Johns R. 2020. [Tracking insect outbreaks: a case study of community-assisted moth monitoring using sex pheromone traps](publications/2020/Carletonetal2020.pdf){target="_blank"}. FACETS 5(1): 91-104

Cottrell S, Mattor KM Morris JL, Fettig CJ, McGrady P, Maguire DY, **James PMA**, Clear J, Wurtzebach Z, Wei Y, Brunelle A, Western J, Maxwell R, Rotar M, Gallagher L, Roberts R. 2020. [Adaptive capacity in social-ecological systems: A framework for addressing bark beetle disturbances in natural resource management](publications/2020/Cottrelletal2020.pdf){target="_blank"}. Sustainability Science 15(2): 555-567

### 2019

**James PMA** & Huber D. 2019. [TRIA-Net: 10 years of collaborative research on turning risk into action for the mountain pine beetle epidemic](publications/2019/JamesAndHuber2019.pdf){target="_blank"}. Canadian Journal of Forest Research 49(12): iii-v

Larroque J, Legault S, Johns R, Lumley L, Cusson M, Renaut S, **James PMA**. 2019. [Temporal variation in spatial genetic structure during population outbreaks: distinguishing among different potential drivers of spatial synchrony](publications/2019/Larroqueetal2019.pdf){target="_blank"}. Evolutionary Applications 12(10): 1931-1945

Johns R, Bowden J, Carleton D, Cooke B, Edwards S, Emilson E, **James PMA**, Kneeshaw D, MacLean D, Martel V, Moise E, Mott G, Norfolk C, Owens E, Pureswaran D, Quiring D, Regniere J, Richard B, Stastny M. 2019. [A conceptual framework for a spruce budworm Early Intervention Strategy: can outbreaks be stopped?](publications/2019/Johnsetal2019.pdf){target="_blank"}. Forests 10(10):910

Tourne DCM, Ballester MVR, **James PMA**, Martorano LG, Thomas E. 2019. [Strategies to optimize modelling habitat suitability of Bertholletia excelsa in the Pan-Amazonia](publications/2019/Tourneetal2019.pdf){target="_blank"}. Ecology and Evolution 9(22): 12623-12638

Mayrand P, Filotas É, Wittische J, **James PMA**. 2019. [Interactions between spatial and demographic processes inflate the false discovery rate of loci under selection during geographic range expansion](publications/2019/Mayrandetal2019.pdf){target="_blank"}. Genome. 62(11): 715-727

Wittische J, Janes J, **James PMA**. 2019. [Modelling landscape genetic connectivity of the mountain pine beetle in western Canada](publications/2019/Wittischeetal2019.pdf){target="_blank"}. Canadian Journal of Forest Research. 49: 1339–1348

Sujii PS, Nagaib ME, Zucchic MI, Brancaliond PHS, **James PMA**. 2019. [A genetic approach for simulating persistence of reintroduced tree species populations in forest restoration areas](publications/2019/Sujiietal2019.pdf){target="_blank"}. Ecological Modeling, 403, 35-43.

Burns I, Coltman DW, **James PMA**, Cullingham CI. 2019. [Spatial and genetic structure of the lodgepole x jack pine hybrid zone](publications/2019/Burnsetal2019.pdf){target="_blank"}. Canadian Journal of Forest Research 49(7): 844-853.

### 2018

Cullingham C, Janes J, **James PMA**, Hamelin R, Murray B, Sperling F. 2018. [The contribution of genetics and genomics to understanding the ecology of the mountain pine beetle system](publications/2018/Cullinghametal2018.pdf){target="_blank"}. Canadian Journal of Forest Research. 49(7), 721-730.

Legault S and **James PMA**. 2018. [Parasitism rates of spruce budworm larvae: testing the enemy hypothesis along a gradient of forest diversity measured at different spatial scales](publications/2018/LegaultAndJames2018.pdf){target="_blank"}. Environmental Entomology. 47(5): 1083-1095

Marrec R, Pontbriand-Paré O, Legault S, and **James PMA**. 2018. [Spatiotemporal variation in drivers of parasitoid metacommunity structure in continuous forest landscapes](publications/2018/Marrecetal2018.pdf){target="_blank"}. Ecosphere 9(1):e02075

### 2017

Robert L-E, Sturtevant BR, Cooke BJ, **James PMA**, Fortin M-J, Townsend PA, Wolter PT, Kneeshaw D. 2017. [Landscape host abundance and configuration regulate periodic outbreak behavior in spruce budworm (Choristoneura fumiferana Clem.)](publications/2017/Robertetal2017.pdf){target="_blank"}. Ecography

Burke A, Kageyama M, Latombe G, Fasel M, Vrac M, Ramstein G, **James PMA**. 2017. [Risky business: the impact of climate and climate variability on human population dynamics in Western Europe during the Last Glacial Maximum](publications/2017/Burkeetal2017.pdf){target="_blank"}. Quaternary Science Reviews. 164: 217-229

Marcer A, Vidigal DS, **James PMA**, Fortin M-J, Méndez-Vigo B, H. Hilhorst WM, Bentsink L, Alonso-Blanco C, Picó FX. 2017. [Temperature fine-tunes Mediterranean Arabidopsis thaliana life-cycle phenology geographically](publications/2017/Marceretal2017.pdf){target="_blank"}. Plant Biology

### 2016

Ruppert JLW, **James PMA**, Taylor EB, Rudolfsen T, Veillard M, Davis CS, Watkinson D, Poesch MS. 2016. [Riverscape genetic structure of a threatened and dispersal limited freshwater species, the Rocky Mountain Sculpin (Cottus sp.)](publications/2016/Ruppertetal2016.pdf){target="_blank"}. Conservation Genetics

**James PMA**, Robert, LE, Wotton BM, Martel D, Fleming RA. 2016. [Lagged cumulative spruce budworm defoliation affects the risk of fire ignition in Ontario, Canada](publications/2016/Jamesetal2016.pdf){target="_blank"}. Ecological Applications. 27(2): 532-544

Lévesque D, Hudon C, **James PMA**, & Legendre P. 2016. [Environmental factors structuring benthic primary producers at different spatial scales in the St. Lawrence River (Canada)](publications/2016/Levesqueetal2016.pdf){target="_blank"}. Aquatic Sciences, 1-12.

**James PMA**, Janes JK, Roe AD, & Cooke BJ. 2016. [Modeling landscape-level spatial variation in sex ratio skew in the mountain pine beetle (Coleoptera: Curculionidae)](publications/2016/JamesetalB2016.pdf){target="_blank"}. Environmental Entomology. 45(4): 790-801.

### 2015

Maguire DY, **James PMA**, Buddle CM, Bennett EM. 2015. [Landscape Connectivity and Herbivorous Insects: A Framework for Understanding Trade-Offs Between Ecosystem Services](publications/2015/Maguireetal2015.pdf){target="_blank"}. Global Ecology and Conservation. 4: 73-84

**James PMA**, Cooke B, Brunet B, Lumley L, Sperling FAH, Fortin M-J, Quinn V, Sturtevant BR. 2015. [Life-stage differences in spatial genetic structure in an irruptive forest insect: Implications for dispersal and spatial synchrony](publications/2015/Jamesetal2015.pdf){target="_blank"}. Molecular Ecology. 24(2): 296-309.

### 2014

Burke A, Levavasseur G, **James PMA**, Guiducci D, Izquierdo M, Bourgeon L, Kageyama M, Ramstein G. 2014. [Exploring the impact of climate variability during the Last Glacial Maximum on the pattern of human occupation of Iberia. Journal of Human Evolution](publications/2014/Burkeetal2014.pdf){target="_blank"}. 73: 35-46.

Sturtevant BR, Miranda BR, Wolter PT, **James PMA**, Fortin M-J, Townsend PA. 2014. [Forest recovery patterns in response to divergent disturbance regimes in the Border Lakes region of Minnesota (USA) and Ontario (Canada)](publications/2014/Sturtevantetal2014.pdf){target="_blank"}. Forest Ecology and Management. 313(1): 199-211.

### 2013

Burke A, Maíllo Fernández J, Fuertes-Prieto N, Bisson M, **James PMA**, Levavasseur G. 2013. [Archaeological survey in eastern Guadalajara province, Spain: Initial results](publications/2013/Burkeetal2013.pdf){target="_blank"}. Canadian Journal of Archaeology. 37(1): 48-69.

### 2012

Cullingham CI, **James PMA**, Cooke JEK, Coltman DW. 2012. [Characterizing the physical and genetic structure of the lodgepole pine × jack pine hybrid zone: mosaic structure and differential introgression](publications/2012/Cullinghametal2012.pdf){target="_blank"}. Evolutionary Applications. 5(8): 879-891

Samarasekera NG, Bartell NV, Lindgren BS, Cooke JEK, Davis CS, **James PMA**, Coltman DW, Mock KE, Murray BW. 2012. [Spatial genetic structure of the mountain pine beetle (Dendroctonus ponderosae) outbreak in western Canada: historical pattern](publications/2012/Samarasekeraetal2012.pdf){target="_blank"}. Molecular Ecology. 21(12): 2931-2948

Fortin M-J, **James PMA**, MacKenzie A, Melles SJ, Rayfield B. (2012). [Spatial statistics, spatial regression, and graph theory in ecology](publications/2012/Fortinetal2012.pdf){target="_blank"}. Spatial Statistics 1: 100-109.

### 2011

**James PMA**, Murray BW, Hamelin RC, Coltman DW, Sperling FAH. 2011. [Spatial genetic structure of a symbiotic beetle-fungal system: Toward multi-taxa integrated landscape genetics](publications/2011/Jamesetal2011.pdf){target="_blank"}. PLoS ONE 6(10): e25359. 

Roe AR \*, **James PMA** \*, Cooke J, Sperling FAH. 2011. [Spatial community structure of mountain pine beetle fungal symbionts across a latitudinal gradient](publications/2011/Roeetal2011.pdf){target="_blank"}. Microbial Ecology. 62(2): 347-360 \*joint first authorship

**James PMA**, Sturtevant B, Townsend P, Wolter P, Fortin M-J. 2011. [Two dimensional wavelet analysis of spruce budworm host basal area in the Border Lakes Landscape](publications/2011/JamesetalB2011.pdf){target="_blank"}. Ecological Applications 21(6): 2197-2209

**James PMA**, Fortin M-J, Sturtevant BR, Fall A, Kneeshaw DD. 2011. [Modelling spatial interactions among fire, spruce budworm, and logging in the boreal forest](publications/2011/JamesetalC2011.pdf){target="_blank"}. Ecosystems 14: 60-75.

### 2010

Anderson CD, Epperson BK, Fortin M-J, Holderegger R, **James PMA**, Rosenberg MS, Scribner KT, Spear S. 2010. [Considering spatial and temporal scale in landscape-genetic studies of gene flow](publications/2010/Andersonetal2010.pdf){target="_blank"}. Molecular Ecology 19: 3576-3591

Epperson BK, McRae B, Scribner KT, Cushman S, Rosenberg MS, Fortin M-J, **James PMA**, Murphy M, Manel S, Legendre P, Dale M. 2010. [Utility of computer simulations in landscape genetics](publications/2010/Eppersonetal2010.pdf){target="_blank"}. Molecular Ecology 19:3549-3564.

**James PMA**, Fleming RA, Fortin M-J 2010. [Identifying significant scale-specific spatial boundaries using wavelets and null models: Spruce budworm defoliation in Ontario, Canada as a case study](publications/2010/Jamesetal2010.pdf){target="_blank"}. Landscape Ecology. 25: 873-887.

### \< 2010

Rayfield BR, **James PMA**, Fall A, Fortin M-J. 2008. [Comparing static versus dynamic protected areas in dynamic boreal ecosystems](publications/Before2010/Rayfieldetal2008.pdf){target="_blank"}. Biological Conservation. 141(2): 428-449

**James PMA**, Fortin M-J, Fall A, Kneeshaw DD, Messier C. 2007. [The effects of spatial legacies following shifting management practices and fire on boreal forest age structure](publications/Before2010/Jamesetal2007.pdf){target="_blank"}. Ecosystems. 10: 1261-1277

**James PMA**, Rayfield BR, Fall A, Fortin M-J, Farley G. 2005. [Reserve network design combining spatial graph theory and species’ spatial requirements](publications/Before2010/Jamesetal2005.pdf){target="_blank"}. Geomatica. 59(3): 121-129

### Book Chapters

Doyon F, Sturtevant BR, Papaik M, Fall A, Miranda B, Kneeshaw DD, Messier C, Fortin M-J, **James PMA**. 2011. Assessing knowledge ambiguity in the creation of a model based on expert knowledge and comparison with the results of a landscape succession model in central Labrador. In: Expert Knowledge and its Application in Landscape Ecology. Perera A (Ed.). Springer. [Read it here](http://www.springer.com/life+sciences/ecology/book/978-1-4614-1033-1).

**James PMA**, Fortin M-J. 2012. Ecosystems and Spatial Patterns. Encyclopaedia of Sustainability Science and Technology. Springer Science.

### Other Reports

Craven D, Angers VA, Larose-Filotas E, Tittler R, M Desrochers, Messier C, **James PMA** . 2013. L'Aménagement écosystémique des forêts privées du Centre-du-Québec dans le contexte des changements globaux . Rapport Présenté à l'Agence forestière des Bois-Francs, 99 p.
